#CSE 101: Computer Science Principles
####Stony Brook University, Summer 2020

### Lab Exercises Set #6

#### Due: Sunday, July 5, 2020 at 11:59 pm EDT

#### Learning Outcomes
By the end of these exercises you should be able to:
* Use the basic function of numpy to perform computations with vectors of numbers.



### NumPy Array Creation Basics

Run the cell below.

In [ ]:
import numpy as np

Create an array called `a` that contains the values 1, 8, 4, 3 and 9, in that order. Display the contents of `a`.

In [ ]:
a = np.array([1,8,4,3,9])
a

array([1, 8, 4, 3, 9])

Create a 2D array called `a` that contains the values 1, 8, 4, 3, 9 in the first row; 8, 5, 4, 3, 1 in the second row; and 0, 1, 5, 2, 3 in the third row. Display the contents of `a`.

In [ ]:
a = np.array([[1,8,4,3,9], [8,5,4,3,1], [0,1,5,2,3]])
a

array([[1, 8, 4, 3, 9],
       [8, 5, 4, 3, 1],
       [0, 1, 5, 2, 3]])

Using `arange`, create an array called `a` that contains the values 3, 7, 11, 15, ..., 43, in that order. Display the contents of `a`.

In [ ]:
a = np.arange(3, 43, 4)
a

array([ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39])

Using `zeros`, create an array called `a` that contains 8 zeroes.

In [ ]:
a = np.zeros(8)
a

array([0., 0., 0., 0., 0., 0., 0., 0.])

### NumPy Array Slicing

Using `arange`, create an array called `a` that contains the values 1, 2, 3, ..., 20. Use slicing to display the even values in `a`.

In [ ]:
a = np.arange(1,20)
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

Using `arange`, create an array called `a` that contains the values 1, 2, 3, ..., 20. Use slicing to display the values at indices 0, 3, 6, 9, 12, 15, 18.

In [ ]:
a = np.arange(1,20)
a[:19:3]

array([ 1,  4,  7, 10, 13, 16, 19])

Using any means you wish, create a 2D array of integers with 4 rows and 6 columns called `a`. Include a mixture of positive and negative values. Display `a`.

In [ ]:
import random
numbers = list(range(-12,12))
a = np.array([list(random.sample(numbers,6)) for i in range(4)])
a

array([[ -6,  -8,  -5,  -1, -10,   5],
       [-10,  -6,  -4,   2,   1,   9],
       [-12,  -1,  10,   5,  -3,  -7],
       [  9,  10,   7,  -3,  -4,  -8]])

Using slicing, display column 3.

In [ ]:
print(a[:,3])

[-1  2  5 -3]


Using slicing, display the elements from rows #0 and 1, and columns #2 through 5 (inclusive).

In [ ]:
print(a[:2,2:6])

[[ -5  -1 -10   5]
 [ -4   2   1   9]]


Using the slicing notation that can accept conditions, display the values in `a` that are multiples of 2 or multiples of 3.

In [ ]:
a[(a % 2 == 0) | (a % 3 == 0)]

array([ -6,  -8, -10, -10,  -6,  -4,   2,   9, -12,  10,  -3,   9,  10,
        -3,  -4,  -8])

Using the slicing notation that can accept conditions, display the values in `a` that are less than 0.

In [ ]:
a[a<0]

array([ -6,  -8,  -5,  -1, -10, -10,  -6,  -4, -12,  -1,  -3,  -7,  -3,
        -4,  -8])

### NumPy Arithmetic

Using any means you wish, create an array of 6 integers called `salaries`. Then, add the constant 100 to each value using NumPy syntax. This should require only one line of code. Display the array resulting from this addition.

In [ ]:
salaries = np.array([22,12,370,582,10,65])
salaries += 100
salaries

array([122, 112, 470, 682, 110, 165])

Using any means you wish, create a 2D array of integers with 4 rows and 6 columns called `a`. Include a mixture of positive and negative values. Display the sum of the values in row 1.

In [ ]:
import random
numbers = list(range(-12,12))
a = np.array([list(random.sample(numbers,6)) for i in range(4)])
a

array([[  0,   7, -11,   4,   2,   9],
       [ 11,  -8,   3,  -1,  -4,  -2],
       [ 10,   1, -10,   7,  -3,  -6],
       [ -3,   5,  10,  -6,  -1,   0]])

Display the sum of the values in column 4.

In [ ]:
a[:,4].sum(axis=0)

-6

Display the mean of the values in column 3.

In [ ]:
a[:,3].mean(axis=0)

1.0

Display the minimum value in row 2.

In [ ]:
a[2,:].min()

-10

### pandas Basics

Download [MSFT.csv](https://drive.google.com/file/d/1rxZuezqHl3D8cw7aV9GcEMo--ZULibkQ/view?usp=sharing) and upload it to Colab.

Use the `read_csv` function from pandas to load the contents into a dataframe called `df`.

In [ ]:
import pandas as pd

df = pd.read_csv('MSFT.csv')

Use `head` to display the top 5 rows of `df`.

In [ ]:
df.head(5)

Date        Open        High  ...       Close   Adj Close    Volume
0  2020-04-24  172.059998  174.559998  ...  174.550003  174.065216  34305300
1  2020-04-27  176.589996  176.899994  ...  174.050003  173.566605  33194400
2  2020-04-28  175.589996  175.669998  ...  169.809998  169.338379  34392700
3  2020-04-29  173.220001  177.679993  ...  177.429993  176.937210  51286600
4  2020-04-30  180.000000  180.399994  ...  179.210007  178.712280  53661300

[5 rows x 7 columns]

Use `describe` to display summary statistics.

In [ ]:
df.describe()

Open        High         Low       Close   Adj Close        Volume
count   42.000000   42.000000   42.000000   42.000000   42.000000  4.200000e+01
mean   184.598332  186.887142  182.517143  184.876906  184.662569  3.524687e+07
std      6.730425    6.878747    6.969385    6.913251    7.065358  7.986193e+06
min    172.059998  174.559998  169.389999  169.809998  169.338379  2.082690e+07
25%    180.649997  183.749996  177.724998  181.442497  181.442497  3.047832e+07
50%    184.275002  185.895004  182.419998  183.555001  183.339996  3.320300e+07
75%    186.685001  190.162499  184.332500  187.605003  187.605003  4.137882e+07
max    202.089996  203.949997  201.429993  201.910004  201.910004  5.366130e+07

Display the averages of the columns.

In [ ]:
df.mean(axis=0)

Open         1.845983e+02
High         1.868871e+02
Low          1.825171e+02
Close        1.848769e+02
Adj Close    1.846626e+02
Volume       3.524687e+07
dtype: float64

Display the first 5 values in the column labeled "Close".

In [ ]:
df['Close'].head(5)

0    174.550003
1    174.050003
2    169.809998
3    177.429993
4    179.210007
Name: Close, dtype: float64

Sort the "Close" column into *descending* order and display the top 5 rows.

In [ ]:
df.sort_values(by='Close').head(5)

Date        Open        High  ...       Close   Adj Close    Volume
2  2020-04-28  175.589996  175.669998  ...  169.809998  169.338379  34392700
1  2020-04-27  176.589996  176.899994  ...  174.050003  173.566605  33194400
0  2020-04-24  172.059998  174.559998  ...  174.550003  174.065216  34305300
5  2020-05-01  175.800003  178.639999  ...  174.570007  174.085175  39370500
3  2020-04-29  173.220001  177.679993  ...  177.429993  176.937210  51286600

[5 rows x 7 columns]

### How to Submit Your Work

1. Go to the [course website](https://sites.google.com/stonybrook.edu/cse-101/schedule?authuser=0).

1. Click the **Submit** link for this assignment.

1. Type your SBU ID# on the line provided.

1. Press the button marked **Add file**.

1. Click the **My Drive** tab.

1. Click on the file you wish to submit.

1. Hit **Select**.

1. Hit **Submit** to submit your file grading.